title: Zhenghao Wang's Homepage
page-top-title: Zhenghao Wang
top-section-bg-text: Applied Physics
home-subtitle: Zhenghao Wang&ensp;|&ensp;王政浩
copyright-text: '&copy; Zhenghao Wang 2025. All Rights Reserved.'
